<?php

function civimigrate_menu() {
  return array(
    'civimigrate-mapper' => array(
      'page callback' => 'civimigrate_callback',
      'access arguments' => array(
        'administer nodes'
      ),
      'type' => MENU_CALLBACK
    ),
    'civimigrate-mapper/%cmid/edit' => array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
        'civimigrate_form',
        1
      ),
      'type' => MENU_CALLBACK,
      'access arguments' => array(
        'administer nodes'
      )
    )
  );
}

function cmid_load($cmid) {
  $results = db_query("SELECT * FROM {civimigrate_mappings} WHERE cmid = :cmid", array(
    ':cmid' => $cmid
  ));
  $cmid = array();
  foreach ($results as $result) {
    $cmid = array(
      'cmid' => $result->cmid,
      'source_field' => $result->source_field,
      'destination_field' => $result->destination_field,
      'description' => $result->description,
      'table' => $result->table,
      'issuegroup' => $result->issuegroup
    );
  }
  return $cmid;
}

function civimigrate_callback() {
  drupal_set_title("Civimigrate_mappings table");
  $results = db_query("SELECT * FROM {civimigrate_mappings}");
  $table = array(
    'header' => array(
      'cmid',
      'source_field',
      'destination_field',
      'description',
      'table',
      'issuegroup',
      'Edit'
    ),
    'rows' => array()
  );
  foreach ($results as $result) {
    $table['rows'][] = array(
      $result->cmid,
      $result->source_field,
      $result->destination_field,
      $result->description,
      $result->table,
      $result->issuegroup,
      l('Edit', "civimigrate-mapper/{$result->cmid}/edit")
    );
  }
  return theme('table', $table);
}

function civimigrate_form($form, &$form_state, $cmid) {
  drupal_set_title("Editing mapping {$cmid['cmid']}");
  $form['source_field'] = array(
    '#title' => 'Source Field',
    '#type' => 'textfield',
    '#default_value' => $cmid['source_field']
  );
  $form['destination_field'] = array(
    '#title' => 'Destination Field',
    '#type' => 'textfield',
    '#default_value' => $cmid['destination_field']
  );
  $form['description'] = array(
    '#title' => 'Description',
    '#type' => 'textarea',
    '#default_value' => $cmid['description']
  );
  $form['table'] = array(
    '#title' => 'Table',
    '#type' => 'textfield',
    '#default_value' => $cmid['table']
  );
  $form['issuegroup'] = array(
    '#title' => 'Issue Group',
    '#type' => 'textfield',
    '#default_value' => $cmid['issuegroup']
  );
  $form['cmid'] = array(
    '#type' => 'hidden',
    '#value' => $cmid['cmid']
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save'
  );
  return $form;
}

function civimigrate_form_validate($form, &$form_state) {
  foreach ($form_state['values'] as $key => $value) {
    $value = trim($value);
    if (empty($value) && $value != 0) {
      $form_state['values'][$key] = NULL;
    }
  }
}

function civimigrate_form_submit($form, &$form_state) {
  $record = array(
    'source_field' => $form_state['values']['source_field'],
    'destination_field' => $form_state['values']['destination_field'],
    'description' => $form_state['values']['description'],
    //'table' => $form_state['values']['table'],
    'issuegroup' => $form_state['values']['issuegroup']
  );
  $result = db_update('civimigrate_mappings')->fields($record)->condition('cmid', $form_state['values']['cmid'])->execute();
  drupal_set_message("$result row(s) updated.");
  drupal_goto('civimigrate-mapper');
}
